# Generated by Django 3.2.9 on 2021-12-02 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('dealersName', models.TextField(verbose_name='DealersName')),
                ('zipcode', models.CharField(max_length=15, verbose_name='zipcodex')),
                ('zipcode_2', models.CharField(max_length=15, verbose_name='zipCode')),
                ('state', models.CharField(max_length=5, verbose_name='state')),
                ('address', models.TextField(verbose_name='Address')),
                ('dealerId', models.IntegerField(primary_key=True, serialize=False, verbose_name='ids')),
            ],
        ),
        migrations.CreateModel(
            name='Userpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.CharField(max_length=4)),
                ('Mileage', models.CharField(max_length=8)),
                ('Make', models.CharField(max_length=50)),
                ('Model', models.CharField(max_length=50)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('email', models.EmailField(max_length=254)),
                ('date_published', models.DateField(default=django.utils.timezone.now)),
                ('zipCode', models.CharField(max_length=5)),
                ('image', models.ImageField(blank=True, null=True, upload_to='C:\\Users\\gabri\\Desktop\\test\\ecommerce\\static\\images')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DealershipListing',
            fields=[
                ('carID', models.IntegerField(primary_key=True, serialize=False, verbose_name='CarID')),
                ('price', models.IntegerField(max_length=30, verbose_name='price')),
                ('msrp', models.IntegerField(max_length=30, verbose_name='msrp')),
                ('mileage', models.IntegerField(max_length=9, verbose_name='mileage')),
                ('is_new', models.BooleanField(max_length=5, verbose_name='isNew')),
                ('model', models.CharField(max_length=255, verbose_name='Models')),
                ('make', models.CharField(max_length=255, verbose_name='Make')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('dealerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.dealer')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
