# Generated by Django 3.2.9 on 2021-12-02 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealershiplisting',
            name='is_new',
            field=models.BooleanField(verbose_name='isNew'),
        ),
        migrations.AlterField(
            model_name='dealershiplisting',
            name='mileage',
            field=models.IntegerField(verbose_name='mileage'),
        ),
    ]
