# Generated by Django 3.2.9 on 2021-12-02 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealer',
            old_name='ids',
            new_name='dealerId',
        ),
    ]
