# Generated by Django 3.2.9 on 2021-12-02 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20211202_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealershiplisting',
            name='msrp',
            field=models.IntegerField(verbose_name='msrp'),
        ),
        migrations.AlterField(
            model_name='dealershiplisting',
            name='price',
            field=models.IntegerField(verbose_name='price'),
        ),
    ]
